### PR TITLE
throwt print util

### LINKED ISSUE #48: `yk::throwt` needs a companion utility that unpacks and prints the underlying stacktrace
This feature should go to a separate header, since yk_util is currently header-only and the inclusion of extra headers are too costly for error-throwing functionality.

Example implementation:

```cpp
#include <boost/exception/get_error_info.hpp>

#include <print>

void printt(const std::exception& e)
{
  if (const auto* const st = boost::get_error_info<traced_type>(e)) {
    std::println("{}\n{}", e.what(), to_string(*st));

  } else {
    std::println(e.what());
  }

  try {
    std::rethrow_if_nested(e);

  } catch (const std::exception& e) {
    printt(e);

  } catch (...) {
    // ...
  }
}
```

### PR DESCRIPTION
**Pull request by yaito3014**
fixes #48

### CODE REVIEW

File: test/main.cpp [hunk 1]
```diff
@@ -324,6 +325,30 @@ BOOST_AUTO_TEST_CASE(Throwt) {
...
+
+  struct my_exception : std::runtime_error, std::nested_exception {
+    using runtime_error::runtime_error;
+  };
+
+  try {
+    try {
+      throw std::runtime_error("foo");
+    } catch (const std::exception& e) {
+      throw my_exception("bar");
```
Comment (saki7) [inline test/main.cpp:345]: Use [std::throw_with_nested](http://en.cppreference.com/w/cpp/error/throw_with_nested)

File: test/main.cpp [hunk 2]
```diff
@@ -324,6 +325,30 @@ BOOST_AUTO_TEST_CASE(Throwt) {
...
+
+  try {
+    throw std::runtime_error("foobar");
+  } catch (const std::exception& e) {
+    std::stringstream ss;
+    yk::printt(ss, e);
+    BOOST_TEST(ss.str() == "foobar\n");
+  }
+
+  struct my_exception : std::runtime_error, std::nested_exception {
```
Comment (saki7) [inline test/main.cpp:337]: Directly inheriting from `std::nested_exception` seems odd, you can just use [std::throw_with_nested](http://en.cppreference.com/w/cpp/error/throw_with_nested)

File: include/yk/detail/traced_type.hpp [hunk 3]
```diff
@@ -0,0 +1,17 @@
+#ifndef YK_DETAIL_TRAICED_TYPE
```
Comment (saki7) [inline include/yk/detail/traced_type.hpp:1]: TRACED

**Review by saki7 — CHANGES_REQUESTED** [review]
Some minor issues

File: include/yk/detail/traced_type.hpp (hunk 3 above)
Comment (yaito3014) [reply include/yk/detail/traced_type.hpp]: fixed in b691adb26b48f26ae3213df11303911f1c3b7ec8

**Review by saki7 — APPROVED** [review]

**Comment by saki7** [comment]
Super LGTM
Super Thanks
